version: '3.9'

services:
  gitlab-server:
    image: gitlab/gitlab-ce:16.7.7-ce.0
    container_name: gitlab-server
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'Abcd@0123456789'
        puma['worker_processes'] = 0 # disable cluster mode to avoid more memory usage
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    ports:
      - '8088:80'
      - '8443:443'
